### ISSUE TITLE
Circuit breaker not resetting

### ISSUE THREAD

**Issue by youngkin** [dahernan/goHystrix#19]
In the NetFlix Hystrix Java implementation an open circuit breaker will reset itself (i.e., close) after [`circuitBreaker.sleepWindowInMilliseconds`](https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.sleepWindowInMilliseconds). In goHystrix an open circuit breaker will only reset itself if no requests are received during the `NumberOfSecondsToStore` interval. The `NumberOfSecondsToStore` interval is important in defining the rolling window of metrics but it's not enough. A circuit breaker implementation also needs to provide a way for the breaker to periodically allow requests to go through in order to see if the failed dependency has resolved, i.e., it needs to support a 3rd state - [half-open](http://martinfowler.com/bliki/CircuitBreaker.html). 

Do you have any plans to provide a half-open state similar to NetFlix's Hystrix? If not, would you accept a pull request to implement it?

I do like goHystrix's support for access to detailed metrics!

**Comment by dahernan** [comment]
I didn't implement half-open for simplicity, because the `NumberOfSecondsToStore` acts like a leaky bucket forgetting old failed request, in most of the cases that I tried is good enough to health the circuit.
If you think is good to have, feel free to PR, or I can give you contributor access if you want to improve more things.

In production I'm using [breaker](http://github.com/dahernan/breaker) because is simpler and easy to integrate with other 3rd parties metrics.

**Comment by youngkin** [comment]
Thanks for the pointer to [breaker](https://github.com/dahernan/breaker)
